### ISSUE TITLE
Tests does not run

### ISSUE THREAD

**Issue by ingo-h** [flyte/upnpclient#12]
I'm quite new to github and python but want to investigate UPnP. So I cloned the upnpclient and of course run the tests first but get the error message "ImportError: No module named 'mock". Isn't it [unittest.mock](https://docs.python.org/3/library/unittest.mock.html)? I use Python3. What I'm missing?

**Comment by rytilahti** [comment]
Looks like you need to install `mock` package: `pip install mock` worked here.

**Comment by flyte** [comment]
@ingo-h if you want to investigate uPnP then you don't have to run the tests first. They're only really there to help out me and any other developers of this library.
