### ISSUE TITLE
example from README.md does not run

### ISSUE THREAD

**Issue by ingo-h** [flyte/upnpclient#13]
I use Debian GNU/Linux 9.4 (stretch), cloned upnpclient and installed packets following `requirements.txt`. As said in `README.md` the library is running with Python 2 and Python 3, so I installed both versions:
```
~$ git clone https://github.com/flyte/upnpclient.git
~$ sudo apt install --install-recommends python-requests
~$ sudo apt install --install-recommends python3-requests
~$ sudo apt install --install-recommends python-six
~$ sudo apt install --install-recommends python3-six
~$ pip3 install netdisco
~$ sudo apt install --install-recommends python-dateutil
~$ sudo apt install --install-recommends python3-dateutil
~$ sudo apt install --install-recommends python-lxml
~$ sudo apt install --install-recommends python3-lxml
```
Now tried to use the first example with python3:
```
~$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
>>> import upnpclient
>>> devices = upnpclient.discover()
Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.10.119:49153/nmrDescription.xml
Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.10.119:49153/nmrDescription.xml
Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.10.119:49153/nmrDescription.xml
[...]
```
And many more lines like that.

Trying python 2 I get  this:
```
~$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
>>> import upnpclient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "upnpclient/__init__.py", line 143, in <module>
    from upnpclient import const, errors, marshal, soap, ssdp, upnp, util  # noqa: F401
  File "upnpclient/ssdp.py", line 1, in <module>
    from netdisco.ssdp import scan
ImportError: No module named netdisco.ssdp
>>>
```
I want to use python3. How can I fix the error messages?

**Comment by rytilahti** [comment]
Was `devices` not populated correctly? Those errors are coming from invalid/unsupported parts of the device provided interface file, and they may or may not affect the functionality.

For python2 you would need to install netdisco package: `pip install netdisco`.

**Comment by flyte** [comment]
Yeah, as @rytilahti points out, it looks like the `upnpclient.discover()` call is receiving some badly formatted XML from http://192.168.10.119:49153/nmrDescription.xml .

If you paste that file here I may be able to see what's wrong with it. Be careful to remove any potentially secret information from the file first.

**Comment by flyte** [comment]
@ingo-h Closing this for now. Please reopen with the info from my previous comment if you're still having trouble.
