### ISSUE TITLE
description xml file error

### ISSUE THREAD

**Issue by breezecloud** [flyte/upnpclient#15]
hi,
I am use this lib to discove upnp device.
devices = upnpclient.discover() return "error ''\n          SequenceNumber'' for http://192.168.137.131:49152/description.xml"
I think it's return a windows line end xml file.
How can I avoid this error?Can you help me?

**Comment by flyte** [comment]
Hi @breezecloud 

Could you download the `description.xml` file from the device and post it here, making sure to redact any sensitive information first?

A lot of devices return weird non standards-compliant XML, so this may be one of them.

**Comment by breezecloud** [comment]
```xml
<?xml version="1.0"?>^M
<root xmlns="urn:schemas-upnp-org:device-1-0">^M
<specVersion>^M
<major>1</major>^M
<minor>0</minor>^M
</specVersion>^M
<device>^M
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>^M
<friendlyName>UpMpd</friendlyName>^M
<manufacturer>JF Light Industries</manufacturer>^M
<manufacturerURL>https://opensourceprojects.eu/u/medoc/profile/</manufacturerURL>^M
<modelDescription>UPnP front-end to MPD</modelDescription>^M
<modelName>UpMPD</modelName>^M
<modelNumber>1.0</modelNumber>^M
<modelURL>https://opensourceprojects.eu/p/upmpdcli/code/</modelURL>^M
<serialNumber>42</serialNumber>^M
<UDN>uuid:a632e261-f30b-cb3a-cce8-000c29a16e2b</UDN>^M
<serviceList>^M
<service>^M
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>^M
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>^M
<SCPDURL>/upmpd/RenderingControl.xml</SCPDURL>^M
```
"description.xml" 94 lines, 3673 characters

**Comment by breezecloud** [comment]
<?xml version="1.0"?>^M

<root xmlns="urn:schemas-upnp-org:device-1-0">^M

<specVersion>^M

<major>1</major>^M

<minor>0</minor>^M

</specVersion>^M

<device>^M

<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>^M

<friendlyName>UpMpd</friendlyName>^M

<manufacturer>JF Light Industries</manufacturer>^M

<manufacturerURL>https://opensourceprojects.eu/u/medoc/profile/</manufacturerURL>^M

<modelDescription>UPnP front-end to MPD</modelDescription>^M

<modelName>UpMPD</modelName>^M

<modelNumber>1.0</modelNumber>^M

<modelURL>https://opensourceprojects.eu/p/upmpdcli/code/</modelURL>^M

<serialNumber>42</serialNumber>^M

<UDN>uuid:a632e261-f30b-cb3a-cce8-000c29a16e2b</UDN>^M

<serviceList>^M

<service>^M

<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>^M

<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>^M

<SCPDURL>/upmpd/RenderingControl.xml</SCPDURL>^M

"description.xml" 94 lines, 3673 characters

**Comment by breezecloud** [comment]
sorry，an error in first line：
Error 'Invalid URL '192.168.137.1': No schema supplied. Perhaps you meant http://192.168.137.1?' for 192.168.137.1

**Comment by flyte** [comment]
Thanks @breezecloud 

I've added formatting to your comment to help with readability (please have a look [here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for how to do this).

I'll take a look at whether I can deal with this output soon, and I'll update this ticket.

**Comment by breezecloud** [comment]
I get error message：
  File "./test.py", line 5, in <module>
    devices = upnpclient.discover()
  File "/home/luping/cmduplay/upnpclient/upnpclient/ssdp.py", line 18, in discover
    devices[entry.location] = Device(entry.location)
  File "/home/luping/cmduplay/upnpclient/upnpclient/upnp.py", line 132, in __init__
    self._read_services()
  File "/home/luping/cmduplay/upnpclient/upnpclient/upnp.py", line 183, in _read_services
    findtext('eventSubURL')
  File "/home/luping/cmduplay/upnpclient/upnpclient/upnp.py", line 244, in __init__
    self._read_actions()
  File "/home/luping/cmduplay/upnpclient/upnpclient/upnp.py", line 303, in _read_actions
    arg_statevar = self.statevars[findtext('relatedStateVariable')]
KeyError: '\n          SequenceNumber'
is help for debug？

**Comment by breezecloud** [comment]
I've found out the reason, the format of an XML file is a problem, the file has a new line, but I suggest that the program can deal with this problem in function _read_actions
xml file：<relatedStateVariable>
          SequenceNumber</relatedStateVariable>
