### ISSUE TITLE
Travis build fails for Python 3.4

### ISSUE THREAD

**Issue by maiermic** [flyte/upnpclient#21]
Running `pip install upnpclient` in a fresh Python 3.4.* environment tries to install `lxml` version `4.4.0` (as requirement), but

> This lxml version requires Python 2.7, 3.5 or later.

Hence, the Travis build (of branch `develop`) fails for Python 3.4 in the meantime.

**Comment by Calinou** [comment]
CI for Python 3.4 could likely be removed at this point.
