### ISSUE TITLE
No newer releases than 0.0.8 on PyPi

### ISSUE THREAD

**Issue by PureTryOut** [flyte/upnpclient#34]
According to Github this package has a 1.0.2 release, but the latest one on PyPi is 0.0.8. Please update the PyPi package.

Also, `setup.py` seems to have dissapeared so I'm not sure how this should now be installed.

**EDIT:** Never mind I figured out how to install this thing. For any future distro packagers:

```
poetry build --format wheel
pip install --isolated --root="<location to install>" --ignore-installed --no-deps dist/*.whl
```

**Comment by flyte** [comment]
`1.0.3` is now on PyPI, and I've fixed the Travis CI deployment thingy, so new updates should all end up on PyPI automatically again.

I was about to answer how you could build a wheel using poetry, but you've edited, so thanks for that!

**Comment by PureTryOut** [comment]
Thanks!

**Comment by PureTryOut** [comment]
Actually, another question, seems you run tests with tox but how would I run it with pytest? Normally (with a `setup.py` package) I would do `PYTHONPATH="$PWD/build/lib" pytest`, but that directory obviously doesn't exist now.

```
_____________________________________ ERROR collecting tests/test_upnpclient.py _____________________________________
ImportError while importing test module '/home/bart/Documents/Git/alpine/aports/testing/py3-upnpclient/src/upnpclient-1.0.3/tests/test_upnpclient.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_upnpclient.py:15: in <module>
    import upnpclient as upnp
E   ModuleNotFoundError: No module named 'upnpclient'
```

**Comment by flyte** [comment]
Once you've done a `poetry install` and activated the virtualenv with `poetry shell` you should just be able to run `pytest` to run the tests.

```
(upnpclient-ZbLTK6rr-py3.8) flyte@demosthenes:~/dev/upnpclient
$ pytest
==================================================== test session starts =====================================================
platform linux -- Python 3.8.0, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
rootdir: /home/flyte/dev/upnpclient
plugins: cov-2.9.0
collected 74 items                                                                                                           

tests/test_upnpclient.py ..........................................................................                    [100%]

===================================================== 74 passed in 1.66s =====================================================
```

**Comment by PureTryOut** [comment]
Ah yes, virtualenv, I can't use that. This is for distro packaging and virtualenvs are not available here, build systems do not work with that.

I tried just installing it to a temp directory and expanding the PYTHONPATH to there but that didn't do the trick sadly.

**Comment by flyte** [comment]
```
poetry export --dev | pip install -r /dev/stdin
```
Edit: Apologies for the brevity - I'm just trying to get my work done for the week.
