### ISSUE TITLE
SOAP argument order is important

### ISSUE THREAD

**Issue by gstein** [flyte/upnpclient#5]
I have an IGD that expects the AppPortMapping arguments to be in the same order as listed in argsdef_in. However, upnpclient can mix them up. As a result, my IGD returns error 402 (invalid args) and an HTTP Status of 500.

I've verified this by capturing/taking the POST that upnpclient generates, fixing the argument order (and changing nothing else), and sending this modified POST request. It works perfectly.

**Comment by flyte** [comment]
Ah, that makes sense. I'll take a look at the solution this weekend. Cheers

**Comment by flyte** [comment]
@gstein This is now hopefully fixed in `v0.0.5`. Please test it out and let me know.

**Comment by gstein** [comment]
I tested with v0.0.6 and can confirm this now works with my iGD.

Thanks for the quick turnaround!
