### ISSUE TITLE
SOAP Envelope Namespace URI should be terminated with a trailing '/'

### ISSUE THREAD

**Issue by JanOveSaltvedt** [flyte/upnpclient#6]
I believe `NS_SOAP_ENV` in soap.py line 10 should be terminated with an '/'.

From:
```python
NS_SOAP_ENV = 'http://schemas.xmlsoap.org/soap/envelope'
```
To:
```python
NS_SOAP_ENV = 'http://schemas.xmlsoap.org/soap/envelope/'
```

At least that is an issue for one of my devices, which returns a 402 error without the trailing slash. 

Hopefully adding the trailing slash does not brake other devices.

**Comment by flyte** [comment]
You're absolutely right! Here's the line in the spec:

```
REQUIRED element defined by SOAP. xmlns namespace attribute MUST be "http://schemas.xmlsoap.org/soap/envelope/". 
```

Stand by while I fix it..

**Comment by flyte** [comment]
Thanks for the report, @JanOveSaltvedt - v0.0.6 should appear on PyPI presently.
